### ISSUE TITLE
Writing to flash seems to clear the session

### ISSUE THREAD

**Issue by okal** [ring-clojure/ring#182]
I'm doing a redirect as follows:

````clojure
(assoc
  (response/redirect "a-random-url")
  :flash {:status-messages {:error "An error message"}})
````

After the redirect, I find that I'm logged out of my app, with the session being wiped out. Am I doing this wrong or is this an actual bug? I'm very new to Clojure/Ring, so I may be going about this wrong.

**Comment by weavejester** [comment]
The session shouldn't be wiped out, but we do have tests to check that, and they're not failing. You've either hit upon an edge condition, or you're doing something wrong.

Could you give me a little more code so I can try and reproduce the issue?

**Comment by JulianLeviston** [comment]
Or... even better, write a failing test! :) <3

**Comment by okal** [comment]
Just got to work. I'll make some time to do that today :-)

**Comment by weavejester** [comment]
@okal, did you manage to reproduce this error?

**Comment by weavejester** [comment]
Closing due to no response.
