### ISSUE TITLE
wrap-resource fails to detect directory resources inside WildFly

### ISSUE THREAD

**Issue by tobias** [ring-clojure/ring#184]
The fix for #169 now causes directory resource detection to fail for
applications deployed to a WildFly container.

Inside WildFly, `.getResource` returns a `vfs:` URL, which is handled
by the [JBoss Virtual File System](https://developer.jboss.org/wiki/VFS3UserGuide)
subsystem. Since it's not a `file:` URL, `response/url-response`
acquires a connection from the URL and hands it to
`response/jar-directory?`, which checks to see if the connection is a
`java.net.JarURLConnection`. If it isn't, `jar-directory?` returns
nil, causing the connection's stream to be returned as the
response. For `vfs:` URLs, the connection is a
`org.jboss.vfs.protocol.VirtualFileURLConnection`, which does not
inherit from `JarURLConnection`.

From a `VirtualFileURLConnection` we can get a `VirtualFile`, which
has an `isDirectory` method, but I certainly don't want to require
ring to have knowledge of VFS.

One solution would be to expose multimethods that dispatch on the
protocol of the URL, possibly:

* `url-is-directory?`
* `url-content-length`
* `url-last-modified`
* `url-content`

Doing so would allow a separate library to provide the `vfs:`
implementations, and would simplify `url-response`. I'm not crazy
about this idea though, since it exposes internals, and complicates
the namespace somewhat (and how does that balance with the
simplification to `url-response`?). 

I'm happy to discuss alternate solutions, and happy to provide a PR if
we settle on one.

**Comment by weavejester** [comment]
I hadn't anticipated there would be other protocols than `jar:` and `file:`. I think you're right that we need to expose some polymorphic interface to account for this.

Rather than having multiple multimethods, what about if we have a single function that returns a map of information that can then be used to construct a response. Something like `resource-info` or `resource-meta` that would describe the resource at the end of a URL.

**Comment by tobias** [comment]
Yes, a single multimethod returning a map is much better, and I like `resource-info`. I'll try to get a pull request together today.
