### ISSUE TITLE
Support for async handlers

### ISSUE THREAD

**Issue by moshevds** [ring-clojure/ring#188]
Hi,

Has there been any thought about adding support for asynchronous handlers in the Ring Spec?

There are currently a few different Ring compatible servers available, some support async programming styles, but there is no emerging common practice (as far as I can tell).

This is a complicated issue when taking into account receiving request bodies, allowing delayed headers and sending (chunked) response bodies. core.async channels could be a basis for this, but mandate a specific library. Callbacks are an alternative, but might be a less natural fit.

Is this the correct place to start a discussion? Actual implementations and maybe a wrap-asynchronous middleware (for compatibility with synchronous-only adapters) should hopefully be trivial to create.

Thanks.

**Comment by weavejester** [comment]
The best place to discuss this would be on the ring-clojure group.
