### ISSUE TITLE
https only

### ISSUE THREAD

**Issue by acthp** [ring-clojure/ring#190]
Would like to be able to serve only https, no http, with the jetty adapter.

**Comment by icambron** [comment]
Check out https://github.com/ring-clojure/ring-defaults, which provides some middleware for doing just that.

**Comment by weavejester** [comment]
The SSL redirect middleware isn't quite the same thing; Jetty will still serve HTTP, it'll just redirect it to HTTPS.

**Comment by icambron** [comment]
Hmm, true. Now I'm curious what the use case for that is.

**Comment by acthp** [comment]
For which? For only serving https? The reason for only serving https is that opportunistic encryption (e.g. redirect http to https; or client probe for https, fallback to http) doesn't work. A MITM can prevent the client from switching to https by proxying the connection (in the case of redirect), or dropping the https probe (in the case of a client https probe).

We write our client code, so there's no reason to ever serve http.

**Comment by weavejester** [comment]
Fixed by #224.
