### ISSUE TITLE
custom way to get session

### ISSUE THREAD

**Issue by WeweTom** [ring-clojure/ring#191]
usually , we get session by `req-key` (session id) which is stored in HTTP Cookies , as below

```clojure
;; https://github.com/ring-clojure/ring/blob/1.3.1/ring-core/src/ring/middleware/session.clj
;; L17   
  :cookie-name  (options :cookie-name "ring-session")
  ...
;; L26 - L28 
  (let [req-key  (get-in request [:cookies cookie-name :value])
        session  (store/read-session store req-key)
        session-key (if session req-key)]
```

but sometimes , we want to get `req-key` from custom HTTP Headers , like this

```clojure
  (let [req-key  (or (my-custom-req-key-getter request) (get-in request [:cookies cookie-name :value]))
        session  (store/read-session store req-key)
        session-key (if session req-key)]
```

`(my-custom-req-key-getter request)`  is my custom fn to get `req-key` (session id) 

so , my question is ,  is there a way to do these kind of thing?

 PS:   my usage scenario is : I wrote a mobile app that need delivery `req-key` (session id) ,  I can not write  cookie, but I can set custom HTTP Headers

**Comment by weavejester** [comment]
You'll need to write your own middleware to achieve that. It's not something the session middleware in Ring supports.
