### ISSUE TITLE
Upgrade javax.servlet to 3.1(?)

### ISSUE THREAD

**Issue by mumrah** [ring-clojure/ring#192]
Preface: I'm looking at Ring from a 10k foot view - I haven't used it much directly, but it's a big part of the project I work on.

Lots of nice features were added in JSR315 and JSR340 (Servlet API 3.0 and 3.1, respectively). The big ones being async responses and support for websockets (actually any HTTP Upgrade). It looks like ring is not bound to 2.5 for any particular reason.

Are there plans (or even general interest) for upgrading to a more modern Servlet API?

**Comment by mvitz** [comment]
See #183

**Comment by weavejester** [comment]
What would be the purpose? Servlet API 3.0 and 3.1 are backward compatible with 2.5, as far as I'm aware, so by using version 2.5 we're supporting the widest range of servlet containers.

The later versions of the Servlet API do have new features, but none that Ring currently uses, so I don't see a reason to update the minimum servlet version Ring depends on.

**Comment by mumrah** [comment]
Async responses would be a very nice addition, IMO. The servlet integration looks pretty simple, maybe you could offer "ring-servlet-2.5" and "ring-servlet-3.0"?

**Comment by weavejester** [comment]
Async will require a significant update to the Ring SPEC (or a new SPEC entirely), and there is no obvious consensus on the design. It's likely that this will first be tested in a separate library (e.g. ring/ring-async).

Since Servlet 3.0 is backward compatible with 2.5, Ring currently works with both versions, so I'm not sure what you mean by a "ring-servlet-3.0" library.

**Comment by mumrah** [comment]
Thanks for the explanation, makes sense about the SPEC. Regarding "ring-servlet-[2.5|3.0]", I was suggesting that as one way to keep compatibility for people running older servlet containers (e.g., Jetty 6).

Feel free to close the issue.
