### ISSUE TITLE
Keywordize? option for wrap-params middleware

### ISSUE THREAD

**Issue by sethkrasnianski** [ring-clojure/ring#198]
I noticed that wrap-json-body middleware has option `keywordize?` which turns the keys a body map to keywords. This is an incredibly useful feature. However when utilizing the wrap-params middleware, I am forced to also use the wrap-keyword-params middleware in order to convert the params into a key map.

While this isn't a deal breaker for me, it would be great to consolidate the wrap-keywords-params functionality into the wrap-params middleware. This would allow wrap-params to accept `keywordize?` as an option and produce the same result as if you were to include the wrap-keyword-params middleware.

**Comment by weavejester** [comment]
Idiomatic Clojure favors "simple" over "easy". Having one middleware that converts strings into keywords is simpler than building the same functionality into several different middleware.

**Comment by sethkrasnianski** [comment]
That makes sense. Was it just simpler to implement the `keywordize?` option in the wrap-json-body middleware?
