### ISSUE TITLE
How to get an URL fragment (data after #)?

### ISSUE THREAD

**Issue by igrishaev** [ring-clojure/ring#207]
Hi!
I've just realised that Facebook redirects to my side with the querystring located after hash symbol. For example:
`/foo/bar/?#token=AAA&expires=12345`
That's because of security issues. The thing is, there are no any of `:uri` or `:hash` in the request object that could help me to parse the token.
Should I search for some middleware or Java classes?

Thanks,
Ivan.

**Comment by JulianLeviston** [comment]
The fragment isn't sent to the server. See this: http://stackoverflow.com/questions/8033537/getting-hash-parameters-from-request-url

**Comment by igrishaev** [comment]
Oh year, I've forgot about that. Thank you.
