### ISSUE TITLE
wrap-cookies-accepts-expires-from-clj-time test fails in non-english locale

### ISSUE THREAD

**Issue by patrox** [ring-clojure/ring#209]
The above test (located in ring-core - cookies.clj) failed for me in an untouched master branch:

```
FAIL in (wrap-cookies-accepts-expires-from-clj-time) (cookies.clj:146)
expected: (= {"Set-Cookie" #{"a=b" "HttpOnly" "Path=/" "Secure" (str "Expires=" expires)}} (split-set-cookie (:headers resp)))
  actual: (not (= {"Set-Cookie" #{"a=b" "HttpOnly" "Expires=Thu, 31 Dec 2015 00:00:00 +0000" "Path=/" "Secure"}} {"Set-Cookie" #{"Expires=Cz, 31 gru 2015 00:00:00 +0000" "a=b" "HttpOnly" "Path=/" "Secure"}}))
```

The reason is quite simple - the expected expire date is hardcoded to be:
```
Thu, 31 Dec 2015 00:00:00 +0000
```
while the actual (return from a ```date-time``` call) is formatted according to the default locale -
which in my case turns out to be:
```
Cz, 31 gru 2015 00:00:00 +0000
```

**Comment by weavejester** [comment]
This issue is caused by clj-time/clj-time#185, but we shouldn't rely on a clj-time fix, as the dependency tree may contain an older version of clj-time. Instead, we should add a `with-locale` to force the `:rfc822` formatter to be compliant.
