### ISSUE TITLE
Is there an easy way to support X-Forwarded-Proto?

### ISSUE THREAD

**Issue by Jae** [ring-clojure/ring#215]
https://github.com/ring-clojure/ring/blob/master/ring-jetty-adapter/src/ring/adapter/jetty.clj#L33

from what I gather I just need to add customizer like below.

`httpConfig.addCustomizer( new org.eclipse.jetty.server.ForwardedRequestCustomizer() );`

Would you have suggestion as to how to support X-Forwarded-Proto header for jetty?

**Comment by weavejester** [comment]
This is more a question than an issue, so the [Ring Google Group](http://groups.google.com/group/ring-clojure) would be a more appropriate place to ask this.

By "support X-Forwarded-Proto", I assume that you want to rewrite the request to make the use of a HTTP proxy to be transparent. In Ring, such functionality is handled by [middleware](https://github.com/ring-clojure/ring/wiki/Concepts#middleware).

The [ring-headers](https://github.com/ring-clojure/ring-headers) library contains a `wrap-forwarded-remote-addr` function, and the [ring-ssl](https://github.com/ring-clojure/ring-ssl) library contains a `wrap-forwarded-scheme` function. These change the `:remote-addr` and `:scheme` keys to the values the proxy forwards.

The [ring-defaults](https://github.com/ring-clojure/ring-defaults) library contains both these middleware functions, which it applies if the `:proxy` option is `true`.

**Comment by Jae** [comment]
ah thanks!
