### ISSUE TITLE
java.lang.AssertionError when using cookie-store

### ISSUE THREAD

**Issue by mikos** [ring-clojure/ring#217]
I'm trying to use cookie-store to prevent my Compojure app from losing all session information each time I save a file. I'm getting this assertion error which seems to point to `serialize` (line 65 of ring.middleware.session.cookie).

```
Assert failed: (= x (edn/read-string %))
```

**Comment by weavejester** [comment]
You're trying to store something in the cookie-store that can't be serialized as edn.

**Comment by mikos** [comment]
Thanks @weavejester, I was reading a DATETIME in from SQL and it was being stored as an #inst.
