### ISSUE TITLE
Upgrading from Ring 1.2.1 to Ring 1.4.0 breaks my custom error handler

### ISSUE THREAD

**Issue by sdegutis** [ring-clojure/ring#222]
- `wrap-reload` seems to completely not work at all anymore
- my own `wrap-error` is somehow bypassed in favor of Ring (or Jetty?) using its own exception handler

**Comment by weavejester** [comment]
You'll need to provide a little more information than that. Could you provide a repository or some sample code demonstrating the conditions in which `wrap-reload` fails? Could you also provide the source for your `wrap-error` middleware?

**Comment by sdegutis** [comment]
Never mind the `wrap-reload` part. It turns out to be a bug in `clojure.core/reload`: when you have namespace A with (def a [B/foo]) and namespace B with (def b [C/bar]) then it doesn't matter if you (require 'C :reload), because A/a will still be [[C/bar]] with the old version of C/bar, not the new reloaded one.

The error one is still a problem though. Will get the source in a second.

**Comment by sdegutis** [comment]
Here's my wrap-errors:

~~~clj
(defn wrap-errors [handler]
  (fn [request]
    (try
      (handler request)
      (catch Exception e
        (println)
        (.printStackTrace e)
        {:body "error"
         :status 500}))))
~~~

**Comment by weavejester** [comment]
There doesn't appear to be anything wrong with your middleware function. It works fine for me. Could the exception be occurring outside the middleware? Is `wrap-errors` your outermost middleware function?

**Comment by sdegutis** [comment]
It's not the outmost middleware function, it's closest to the routes and applied before any other middlware. Perhaps it should be applied at the end of the `->` instead, i.e. outside all other middleware.

**Comment by weavejester** [comment]
If it's applied inside the other middleware, then it won't catch errors thrown by the outer middleware. Typically error middleware should be the outmost one.

**Comment by sdegutis** [comment]
Putting it outside all other middlware also does not make my error handler show.

**Comment by sdegutis** [comment]
I have verified that my error handler is being used in some cases, just not this specific one. So it's probably related to some Java initialization happening inside an `(ns (:import ...))` and thus mostly unrelated to Ring.

**Comment by weavejester** [comment]
Shall I close the issue, then?

**Comment by sdegutis** [comment]
I got it.
