### ISSUE TITLE
Restricting to valid cookie attribute is too strict

### ISSUE THREAD

**Issue by wyegelwel** [ring-clojure/ring#232]
The [RFC dealing with cookies](http://tools.ietf.org/html/rfc6265) describes 6 attributes that a user agent is expected to handle. Under [Set-Cookie semantics](http://tools.ietf.org/html/rfc6265#section-4.1.2) and again while describing the algorithm for parsing the attributes (near end of [section 5.2](http://tools.ietf.org/html/rfc6265#section-5.2)), it says to "ignore unrecognized cookie attributes". However, the [ring.middleware.cookies](https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/middleware/cookies.clj) only allows the 6 attributes described in the RFC and throws an exception if an unrecognized attribute exists.

**Comment by j-po** [comment]
I'd like to claim this. I realize that traditionally claiming happens before the first pull request :stuck_out_tongue_closed_eyes:  , but I wanted to make sure it was roughly as complex as I expected first, and ended up just sort of accidentally writing the whole thing. Oops! It wasn't that much work, though, so I'm okay with having to start over for whatever reason if that's warranted.

**Comment by weavejester** [comment]
I've re-read this issue, and I'm not sure I understand it. I had assumed that the issue was about the `Cookie` header on the request, but it appears to be about the `Set-Cookie` header on the response. I'm not sure what the use-case is here, since the response is generated by the handler.
