### ISSUE TITLE
Nested params maps ought to have (positional) ordering guarantees.

### ISSUE THREAD

**Issue by clyfe** [ring-clojure/ring#233]
Let's say I have a query string like this `order[foo]=asc&order[bar]=desc`.
Nested params middleware will turn it into map `{:order {:foo "asc" :bar "desc"}}`.
When turning it into a database query, the order is important.
If there are under or exactly [8][1] entries I get a `clojure.lang.PersistentArrayMap` and that has ordering guarantees.
If there are more than [8][1] entries I get a `clojure.lang.PersistentHashMap` that looses ordering information.
We should have an implementation with [ordering guarantees][2].

```clojure
(def am (into {} (for [i (range 8)] [i i])))
=> #'user/am
(def hm (into {} (for [i (range 9)] [i i])))
=> #'user/hm
(class am)
=> clojure.lang.PersistentArrayMap
(class hm)
=> clojure.lang.PersistentHashMap
am
=> {0 0, 1 1, 2 2, 3 3, 4 4, 5 5, 6 6, 7 7}
hm
=> {0 0, 7 7, 1 1, 4 4, 6 6, 3 3, 2 2, 5 5, 8 8}
```

[1]: https://github.com/clojure/clojure/blob/master/src/jvm/clojure/lang/PersistentArrayMap.java#L32
[2]: https://github.com/flatland/ordered

**Comment by GetContented** [comment]
Why not convert it into the correct order server side? That way if someone munges the params you'll still be golden.

Relying on convention for your API constraints to satisfy a database ordering requirement feels at least somewhat broken for several reasons. For example, what will happen if someone manually does a request by typing in a URL out of order?

Aside from this, API params should probably be commutative.

**Comment by clyfe** [comment]
> Why not convert it into the correct order server side? [...]
It's just an example. The question if we should have a position-preserving map here goes beyond my particular API issues. 

> Relying on convention for your API constraints to satisfy [...]
Positional ordering is already a thing for nested params vectors, that is when no index is given: `foo[]=1&foo[]=2 => [1 2]`. What are the several reasons you mention ?

> [...] what will happen if someone manually does a request [...]
The same thing that will happen if someone types anything incorrectly, he probably won't get correct a response.

> API params should probably be commutative
I don't see an obvious reason for that, but feel free to share why.

**Comment by weavejester** [comment]
I tend to agree with @GetContented on this. This seems like an unusual scenario, and personally speaking, I wouldn't expect the order of parameter keys to be significant in an API. I also don't like the idea of adding an additional dependency to Ring just to cater for an edge case.

I suggest that if this is something you need, @clyfe, then you could produce an ordered version of the nested parameters middleware and release it as a separate library. If that library proves popular, then we can consider merging it into Ring core. This will also allow the functionality to be available before the next Ring release.

**Comment by clyfe** [comment]
I'm somewhat baffled by the justifications.
The suggestion is sensible, I'll get back with a comment if I build one.
