### ISSUE TITLE
ring.util.request/request-url adds an unnecessary "?"

### ISSUE THREAD

**Issue by pupeno** [ring-clojure/ring#234]
```ring.util.request/request-url``` adds an unnecessary "?" so that if the uri is ```/foo/bar``` it ends up being ```http://example.com/foo/bar?``` When it comes to parsing the URL it's obviously not a problem (well, [most of the time](https://carouselapps.com/2015/09/21/bidi-vs-silk/)) but it doesn't look nice and it's not rebuilding the original URL.

The problem is here:

https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/util/request.clj#L13

```(:query-string request)``` is a blank string, ```""```, not ```nil```.

**Comment by pupeno** [comment]
If you are ok switching to a blank screen check, I'll be happy to submit a PR.

**Comment by weavejester** [comment]
It doesn't add an unnecessary "?". If the request has no query string, the `:query-string` key is `nil`. If the request has an blank query string, the `:query-string` key is `""`. So:

```clojure
{:uri "/example", :query-string nil}   => "/example"
{:uri "/example", :query-string ""}    => "/example?"
{:uri "/example", :query-string "a=b"} => "/example?a=b"

**Comment by pupeno** [comment]
I think in the "" it shouldn't add the ?. In my app, the query string is never nil. Even the the URL from the request specifies no query string, it's still "".

**Comment by pupeno** [comment]
I suppose that if lack of query string resulted in nil and empty query string resulted in "", then, this behaviour, would make sense.

**Comment by weavejester** [comment]
What adapter are you using? It sounds like a bug in whatever Ring adapter you have.

**Comment by pupeno** [comment]
I'm using immutant: https://github.com/carouselapps/ninjatools/blob/master/src/clj/ninjatools/core.clj#L20-L22

**Comment by weavejester** [comment]
You'll need to open an issue with them. The `request-url` has the correct behavior, but it sounds as if their adapter is giving you the wrong result when the URL lacks a query string.

**Comment by pupeno** [comment]
I submitted a bug report here: https://issues.jboss.org/browse/IMMUTANT-587
