### ISSUE TITLE
Multipart request content-length handle as Long

### ISSUE THREAD

**Issue by kennyjwilli** [ring-clojure/ring#235]
I have updated to Pedestal 0.4.1 and when doing so the request content-length is now parsed as a `Long` and updated in the request. Ring should not make any assumptions about the type of the request's content-length. Right now Ring will fail with a `java.lang.Long cannot be cast to java.lang.String` when the request's content-length is of type `Long` instead of type `String` due to the [handling of the request content-length] (https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/util/request.clj#L27).

**Comment by weavejester** [comment]
This is a fault with Pedestal and not Ring. The [SPEC](https://github.com/ring-clojure/ring/blob/master/SPEC#L88) dictates that the request headers should always map Strings to Strings.

**Comment by kennyjwilli** [comment]
Great, thanks.
