### ISSUE TITLE
Sessions endlessly recreated due to :recreate key in metadata never being removed

### ISSUE THREAD

**Issue by svdm** [ring-clojure/ring#241]
The session recreation functionality (added in #196) has a bug when a session store is used that supports the reading and writing of metadata (such as `jdbc-ring-session` or, I suppose, the memory store). When the session middleware writes the session data under a new key, it does not remove the `:recreate` key from its metadata: https://github.com/ring-clojure/ring/blob/fa3fafec17ee43f856591e6d828d9d402212c737/ring-core/src/ring/middleware/session.clj#L46

Next request, the session is loaded with its metadata intact, including the `:recreate` tag. As a result the session data is deleted and written again under a different session ID. This continues indefinitely.

I'd propose changing the `:recreate` case in `bare-session-response` to remove the key from the session value's metadata, before handing it over to the store to be written under a new session ID. I can make a PR if that seems like a good solution.

**Comment by weavejester** [comment]
That seems a reasonable solution. Thanks for the report.
