### ISSUE TITLE
NPE in param parsing middleware on certain query strings

### ISSUE THREAD

**Issue by cespare** [ring-clojure/ring#243]
We occasionally get NPEs in ring's middleware parsing code when we get certain malformed query strings (or post bodies).

Here's a small example:

``` clojure
(require '[ring.middleware.params :as params])
(require '[ring.middleware.nested-params :as nested-params])
(let [app (-> (constantly {:status 200 :body "hello!"})
              nested-params/wrap-nested-params
              params/wrap-params)]
  (app {:uri "/", :query-string "x=%\"%6346#%#/&#736%"})) ;=> NPE
```

The problem arises because `wrap-params` creates a `:params` map with a nil key and then `wrap-nested-params` crashes when it sees that.

``` clojure
(require '[ring.util.codec :as codec])
(codec/form-decode "x=%\"%6346#%#/&#736%") ; => {"x" nil, nil nil}
```

I'm not sure whether `wrap-params` should never produce a nil key, or whether `wrap-nested-params` should ignore nil keys (or both).

**Comment by weavejester** [comment]
Thanks for the report. I believe the `wrap-params` function should ignore keys that have invalid (`nil`) values. There's nothing we can really do with a key that points to an invalid value, and it saves middleware further down the like, like `wrap-nested-params` from worrying about it.

**Comment by cespare** [comment]
> I believe the wrap-params function should ignore keys that have invalid (nil) values.

That sounds fine to me, but the cause of the crash is nil map keys, not nil map values. You can construct a query string that causes the crash by producing a `:params` map with a nil key pointing to a non-nil value: just use the string `"%\"%6346#%#=x"` in the above examples.

``` clojure
(codec/form-decode "%\"%6346#%#=x") ;=> {nil "x"}
```

**Comment by cespare** [comment]
Or maybe I'm misunderstanding what you meant by "keys that have invalid (nil) values" and "keys that have invalid (nil) values".

**Comment by weavejester** [comment]
Oh, well, everything I said goes double for `nil` keys. They definitely shouldn't be produced by `wrap-params`.

**Comment by weavejester** [comment]
Might be fixed by https://github.com/ring-clojure/ring-codec/pull/8. That PR seems to have missed out on a release, so I'll go and release Ring-Codec 1.0.1 and see if that helps.

**Comment by cespare** [comment]
I'm not seeing how `url-decode` is involved here. `wrap-params` eventually calls `codec/form-decode` which calls `codec/form-decode-str` which does

``` clojure
(try
  (URLDecoder/decode encoded (or encoding "UTF-8"))
  (catch Exception _ nil)))
```

(I don't understand why ring-codec implements its own url encoding/decoding but also uses `URLEncoder` and `URLDecoder` for some things, but that's a separate topic.)

**Comment by weavejester** [comment]
Yes, you're right about that PR. The `codec/form-decode` function is unrelated. My mistake.

In case you're interested, the reason Ring-Codec has both `url-decode` and `form-decode` is because they differ slightly in how they handle certain characters.

```clojure
(codec/url-decode "foo+bar")
=> "foo+bar"
(codec/form-decode "foo+bar")
=> "foo bar"
```

The `URLEncoder` and `URLDecoder` classes are misnamed, because they don't perform encoding and decoding for URLs, but for the `application/x-www-form-urlencoded` content type.

**Comment by codahale** [comment]
I just ran into this with a URI of the form `/ts.swf?jsinitfunctio%gn=alert%60PoC%20PoC%20PoC%60`.

**Comment by camdez** [comment]
Proposed solution for this here: https://github.com/ring-clojure/ring-codec/pull/25

**Comment by camdez** [comment]
From my perspective, this issue was resolved with https://github.com/ring-clojure/ring-codec/pull/25. Close? /cc @cespare
