### ISSUE TITLE
How to wrap route/resources with no-cache?

### ISSUE THREAD

**Issue by abellina** [ring-clojure/ring#246]
I am having an issue with html pages being cached by Firefox without allowing revalidation. I'd like to (only for html resources) add a no-cache header. Are there good examples on how to do this?

**Comment by weavejester** [comment]
Take a look at the section on [middleware](https://github.com/ring-clojure/ring/wiki/Concepts#middleware) in the wiki. It provides an example of how to write middleware that applies a content-type header. It should be straightforward to adapt that to add a no-cache header instead, and then you just need a condition to check that the response is HTML.

Also, please use the Google Group for questions about Ring.

**Comment by abellina** [comment]
Thanks! Will do
