### ISSUE TITLE
Suggestion to add ring.util.response/bad-request

### ISSUE THREAD

**Issue by mkaschenko** [ring-clojure/ring#248]
> 10.4.1 400 Bad Request
The request could not be understood by the server due to malformed syntax. The client SHOULD NOT repeat the request without modifications.

http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by mkaschenko** [comment]
Sorry about that.

**Comment by weavejester** [comment]
Sorry about what?

**Comment by mkaschenko** [comment]
I opened the issue which is implemented already.

**Comment by weavejester** [comment]
I don't believe Ring has a `bad-request` method, but it's true you can use `response` and `status`. And there are third-party libraries that provide all the response types as functions.

**Comment by mkaschenko** [comment]
Yes, I found ring-http-response. That's why I closed the issue.
