### ISSUE TITLE
CookieStore fails under Clojure 1.9.0-alpha8

### ISSUE THREAD

**Issue by cemerick** [ring-clojure/ring#252]
The new [namespaced maps](http://dev.clojure.org/jira/browse/CLJ-1910) reader format isn't understood by the version of tools.reader ring-core currently declares, and so:

```clojure
user=> (#'ring.middleware.session.cookie/serialize {::foo 5})

ExceptionInfo Reader tag must be a symbol  clojure.core/ex-info (core.clj:4718)
```

(This comes out of the postcondition on `ring.middleware.session.cookie/serialize`, but only if the session's keys all have the same namespace.)

A workaround is to add a dependency on the latest tools.reader (`[org.clojure/tools.reader "1.0.0-beta3"]`), and upgrading that dep when a final release is made is probably the easiest fix.

A further question might be, why use tools.reader at all instead of `clojure.edn`? "Because `clojure.edn` happened after the last time `cookie.clj` was touched significantly" is probably the answer, but this might be a good time to purge tools.reader if there's no other compelling case for it. This seems to be the only usage, at least in ring itself.

**Comment by weavejester** [comment]
Thanks for the report, I'll update tools.reader. The reason tools.reader is used rather than clojure.edn is because we don't want to be limited by what edn supports. For instance, edn lacks support for Clojure's regular expression syntax.

**Comment by cemerick** [comment]
Got it; the tools.reader alias there ("edn") made me think that edn was the scope of the expected support.

**Comment by cemerick** [comment]
Actually, `cookie.clj` _is_ using `clojure.tools.reader.edn`, so things like regular expressions aren't supported by the cookie store anyway. Maybe you want to expand that support beyond edn, but that's what it's been limited to.

**Comment by weavejester** [comment]
Right, sorry! I think I was getting it mixed up with another part of the system. I should have double-checked.

I believe the reason for using tools.reader is because it was written when Ring supported Clojure 1.3.0, which didn't have the `clojure.edn` namespace. Now that the minimum version of Clojure is 1.5.1, I think we can replace that with `clojure.edn` instead.
