### ISSUE TITLE
Auto Reloading

### ISSUE THREAD

**Issue by karneaud** [ring-clojure/ring#253]
does `auto-reload, auto-refresh and wrap-reload` apply to ._clj and .cljs_ files or **ANY** file within the source/ resource directory?

**Comment by weavejester** [comment]
`auto-reload` and `auto-refresh` are options for [Lein-Ring](https://github.com/weavejester/lein-ring), not Ring.

The `wrap-reload` middleware just applies to Clojure files. It reloads the server files.

**Comment by karneaud** [comment]
oops sorry about that mix up
