### ISSUE TITLE
Support http chunk streaming for StreamableResponseBody

### ISSUE THREAD

**Issue by bendlas** [ring-clojure/ring#254]
There are use cases for passing an asynchronous body in multiple chunks, with time passing in between:

- IFrame Streaming
- HTML5 server sent events

In the current 1.6.0-beta4, `ring.core.protocols/write-body-to-stream`, calls for an unconditional close after a body has been written. That is not sufficient to support chunk streaming.

### Design consideration

An async response could pass a `:chunk` key instead of a `:body` key, to signify that a mere flush is required and that the response fn will be called again with possibly more chunks and a final `:body` or response map w/ no key.

Any `:status` or `:headers` key would be required to be passed with the first chunk.

### Servlet support

Servlet 3's async context supports chunk streaming, by allowing to call [ServletResponse.flushBuffer()](http://docs.oracle.com/javaee/6/api/javax/servlet/ServletResponse.html#flushBuffer()), instead of `ServletOutputStream.close()` after writing a chunk, only calling `.close()` after the final chunk.

### Previous work

In webnf's async-servlet, I punted on a design for the response map and instead opted for multiple callbacks: https://github.com/webnf/webnf/blob/6a2ccaa755e6e40528eb13a5c36bae16ba4947e7/async-servlet/src/clj/webnf/async_servlet.clj#L15

**Comment by weavejester** [comment]
> In the current 1.6.0-beta4, `ring.core.protocols/write-body-to-stream`, calls for an unconditional close after a body has been written. That is not sufficient to support chunk streaming.

Sorry, I'm afraid I don't follow. Why isn't it sufficient?

**Comment by bendlas** [comment]
Because it requires the full body to be written within a single call, where we would like to pass those chunks from multiple events, possibly from different threads.

Consider those ancient chat, that used to push pieces of html into an IFrame. For those we are back at square 1, with the current design: Each browser session ties up a full thread, as long as it's open. Same with SSE.

**Comment by weavejester** [comment]
> Because it requires the full body to be written within a single call

No it doesn't. You are given an `OutputStream`, but this stream can remain open after the `write-body-to-stream` function has returned. That's why it needs to be manually closed.

For instance, let's say you want to extend core.async channels. We might write something like this:

```clojure
(extend-type ManyToManyChannel
  StreamableResponseBody
  (write-body-to-stream [channel response output-stream]
    (take! channel
           (fn write-chunk [chunk]
             (if (nil? chunk)
               (.close output-stream)
               (do (.write output-stream chunk)
                   (.flush output-stream)
                   (take! channel write-chunk))))
```

(In this example `.write` and `.flush` are used directly in the callback function, but in a production implementation we'd pass blocking I/O operations onto an executor with a dedicated threadpool.)

Notice that in the example, `write-body-to-stream` returns immediately, but sets up a callback that will be executed from a separate thread.

**Comment by bendlas** [comment]
I see. I was under the impression, that `write-body-to-stream`'s docstring required an immediate `.close`, with the implementation being dependent on that detail. If a (async) handler is allowed to keep the OutputStream open even with the response commited, this issue is indeed invalid.

**Comment by weavejester** [comment]
I'll try and make the docstring a little clearer. While `write-body-to-stream` is responsible for closing the `OutputStream`, it doesn't need to happen in the same thread.
