### ISSUE TITLE
Async handler is called again every 30 seconds for a single request

### ISSUE THREAD

**Issue by sander** [ring-clojure/ring#257]
It seems like for each request, jetty calls my async handler again every 30 seconds, even though the client has exited.

Example project and log:
https://gist.github.com/sander/34ca8b61c4a1a5c69a334050ec0951e2

I’m using ring 1.6.0-beta4 with the jetty adapter, also tried the current master version.

**Comment by weavejester** [comment]
I'm afraid I can't reproduce the error you're seeing. Are you getting the error consistently?

Could you tell me what OS you're using, and how you're running the server. `lein run` or something more exotic?

I have fixed a bug with Jetty async recently, but the fix hasn't been released as a beta yet. If you're getting this error consistently, I'll create a snapshot of the master branch for you to try.

**Comment by sander** [comment]
Yes, it is consistent at least between two different projects (including the gisted one) and multiple runs. I’m using OS X 10.11.6, Leiningen 2.6.1 on `Java 1.7.0_71 Java HotSpot(TM) 64-Bit Server VM`. I’m running the server with `lein run` indeed.

I have tried `master` including today’s commit 30ea459 by cloning the repository, changing the version in `ring/project.clj` to `1.6.0-SNAPSHOT`, running `lein install` and depending on `[ring "1.6.0-SNAPSHOT"]` in my testing project. The issue still occurred. Is the bug fix in a different branch?

**Comment by sander** [comment]
My current workaround is wrapping the `handler` function:

```
(defonce state
  (atom {:handled #{}}))

(defn app
  [request respond raise]
  (when-not (contains? (@state :handled) request)
    (swap! state update :handled conj request)
    (handler request respond raise)))
```

**Comment by weavejester** [comment]
No, the bug fix is on master (55bf485846e449f8c61745d4deccd2418a5488d7). Did you make SNAPSHOT versions of all the subprojects as well, and update the dependencies between them? Could you give me the output of `lein deps :tree`?

It looks like I'm using the same versions as you, except you're using Java 1.7.0_71 and I'm using Java 1.8.0_25. I'll see if I can get an older version of Java to test this out on.

**Comment by sander** [comment]
Here is `lein deps :tree`:

```clj
 [clojure-complete "0.2.4" :exclusions [[org.clojure/clojure]]]
 [org.clojure/clojure "1.8.0"]
 [org.clojure/tools.nrepl "0.2.12" :exclusions [[org.clojure/clojure]]]
 [ring "1.6.0-SNAPSHOT"]
   [ring/ring-core "1.6.0-beta4"]
     [clj-time "0.11.0"]
       [joda-time "2.8.2"]
     [commons-fileupload "1.3.1"]
     [commons-io "2.5"]
     [crypto-equality "1.0.0"]
     [crypto-random "1.2.0"]
     [org.clojure/tools.reader "0.9.1"]
     [ring/ring-codec "1.0.1"]
       [commons-codec "1.6"]
   [ring/ring-devel "1.6.0-beta4"]
     [clj-stacktrace "0.2.8"]
     [hiccup "1.0.5"]
     [ns-tracker "0.3.0"]
       [org.clojure/java.classpath "0.2.2"]
       [org.clojure/tools.namespace "0.2.10"]
   [ring/ring-jetty-adapter "1.6.0-beta4"]
     [org.eclipse.jetty/jetty-server "9.2.17.v20160517"]
       [javax.servlet/javax.servlet-api "3.1.0"]
       [org.eclipse.jetty/jetty-http "9.2.17.v20160517"]
         [org.eclipse.jetty/jetty-util "9.2.17.v20160517"]
       [org.eclipse.jetty/jetty-io "9.2.17.v20160517"]
   [ring/ring-servlet "1.6.0-beta4"]
```

I did not make SNAPSHOT versions of the subprojects or change any dependencies. If you could create a snapshot I’ll try that with the test project.

**Comment by weavejester** [comment]
Try adding the following dependency to your project:

    [ring/ring-jetty-adapter "1.6.0-beta5-SNAPSHOT"]

This should override the `ring/ring-jetty-adapter` dependency brought in by the `ring` dependency.

**Comment by sander** [comment]
That fixes the issue for me, thanks a lot!

**Comment by weavejester** [comment]
I'll bring out beta5 soon. Thanks for helping diagnose this issue!

**Comment by weavejester** [comment]
Released beta5.

**Comment by mikeandmore** [comment]
I still encounter this bug with 1.6.1. It seems after the client exits, jetty stops calling. However if the client is still processing asynchronously, jetty will still periodically call the handler every 30 seconds.

Is there any way to disable this behavior?

**Comment by weavejester** [comment]
You'll first need to provide a way of reproducing the error you're seeing.

**Comment by arnaudgeiser** [comment]
Got the same issue when doing Server-Sent-Events.
The way to reproduce this problem :

```clojure
(ns ring-sse.core
  (:require
    [compojure.core :refer :all]
    [compojure.route :as route]
    [clojure.core.async :as async :refer :all :exclude [map reduce take into transduce partition merge partition-by]]
    [clojure.data.json :as json]
    [ring.middleware.file :refer :all]
    [clojure.tools.logging :as log]
    [clojure.data.json :as json]
    [clojure.java.io :as io]))

(extend-type clojure.core.async.impl.channels.ManyToManyChannel
ring.core.protocols/StreamableResponseBody
(write-body-to-stream [channel response output-stream]
  (async/go (with-open [writer (io/writer output-stream)]
      (async/loop []
          (doto writer (.write (async/<! channel)) (.flush))
          (recur))))))

(def stream-response
  (partial assoc {:status 200, :headers {"Content-Type" "text/event-stream"}} :body))

(def EOL "\n")

(defn stream-msg [payload]
    (str "data:" (json/write-str payload) EOL EOL))

(defn stream-handler [req res raise]
  (let [ch (chan)]
    (log/debug "New SSE-client")
    (res (stream-response ch))
    (async/go-loop [x 1]
      (async/>! ch (stream-msg x))
      (async/<! (async/timeout 1000))
      (recur (+ x 1)))))


(defroutes app
  (GET "/" []  {:status 200 :headers {"Content-Type" "application/json"} :body "{}"})
  (GET "/stream" [] stream-handler))

(def start
    (-> app
      (wrap-file ".")))
```

Client :

```clojure
(def source (js/EventSource. "/stream"))
(set! (.-onmessage source) (fn [e]
  (log/console.log (.-data e))))
(set! (.-onopen source) (fn [e] (println "connection opened")))
(set! (.-onerror source) (fn [e] (do  (prn "connection closed"))))
```

Every 30 seconds, the log "New SSE-client" will appear and a new stream will be created.
I used @sander solution to work around this problem.

**Comment by weavejester** [comment]
There are a few problems with your code @arnaudgeiser:

```clojure
(extend-type clojure.core.async.impl.channels.ManyToManyChannel
ring.core.protocols/StreamableResponseBody
(write-body-to-stream [channel response output-stream]
  (async/go (with-open [writer (io/writer output-stream)]
      (async/loop []
          (doto writer (.write (async/<! channel)) (.flush))
          (recur))))))
```

First, `clojure.core.async/loop` does not exist. My guess is that it only works in the `go` block because of how core.async transforms the code.

Second, you have no ending conditions to your loop. The stream doesn't close if the channel closes, and vice versa.

You probably want something more like:

```clojure
(extend-type clojure.core.async.impl.channels.ManyToManyChannel
  ring.core.protocols/StreamableResponseBody
  (write-body-to-stream [channel response output-stream]
    (let [writer (io/writer output-stream)]
      (async/go
        (try
          (loop []
            (when-let [value (async/<! channel)]
              (doto writer (.write value) (.flush))
              (recur)))
          (catch java.io.IOException ex
            (log/debug ex))
          (finally
            (async/close! channel)
            (.close channel)))))))
```

However, that alone won't fix your issue, because you're running into the default timeout of Jetty's `AsyncContext` implementation. The easiest solution to this is to change the associated system property to ignore the timeout:

```clojure
(System/setProperty "org.eclipse.jetty.server.HttpChannelState.DEFAULT_TIMEOUT" "0")
```

I'm thinking that this should probably be the default in Ring, as we can handle our own timeouts. I'll open a new issue for this.

**Comment by weavejester** [comment]
Opened #299.

**Comment by arnaudgeiser** [comment]
Indeed, this is not my effective code.
I did some quick and dirty modifications to provide you clues about the current problem (and probably produced invalid code).

Thank you for the work you did on ring.

**Comment by weavejester** [comment]
I think you're running into the async context timeout, so setting the system property I mentioned earlier should solve your problem. Let me know if it does :)

I'll also try to release Ring 1.6.2 sometime in the next day or so, which will set the timeout to 0 by default.

**Comment by arnaudgeiser** [comment]
It's working as expected. :smile:
