### ISSUE TITLE
ring.middleware.keyword-params/keyword-syntax? excludes valid letters

### ISSUE THREAD

**Issue by aldazosa** [ring-clojure/ring#270]
According to the [reader documentation](http://clojure.org/reference/reader), keyword names follow the same rules as symbols. The symbol rules state that:

> Symbols begin with a non-numeric character and can contain alphanumeric characters and *, +, !, -, _, ', and ? (other characters may be allowed eventually).

The current regex assumes that valid non-numeric characters are only ascii letters, which leaves out letters with diacritic symbols (like á, ö or Ď). Using a regex that checks for a unicode character with the "Letter" property should fix this:

```clojure
user> (re-matches #"[A-Za-z*+!_?-][A-Za-z0-9*+!_?-]*" "wéird-näme-2")
nil
user> (re-matches #"[\p{L}*+!_?-][\p{L}0-9*+!_?-]*" "wéird-näme-2")
wéird-näme-2
```

If this seems ok I can make a pull request to change the regex.

**Comment by weavejester** [comment]
That seems fine.
