### ISSUE TITLE
The Expires field in cookies has failed to pre-assert.

### ISSUE THREAD

**Issue by func-hs** [ring-clojure/ring#273]
For example,

When call some Twitter APIs:

```clj
(ns foo
  (:require [clj-http.client :as http]
            [ring.util.response :as ring])
  (:import [clojure.lang ExceptionInfo]))

(try
  (let [response (http/post "https://api.twitter.com/1.1/statuses/show.json")]
    #_"Something to do."
    (ring/status response 200))
  (catch ExceptionInfo e
    #_"Something to do."))
```

In any case, This will return AssertionError.

```
ERROR in (statuses-show-test) (cookies.clj:73)
Uncaught exception, not in assertion.
expected: nil
actual: java.lang.AssertionError: Assert failed: (every? valid-attr? attrs)
Fllowing some stacktraces...
```

This has been failed pre-assert for `ring.middleware.cookies/write-attr-map` because the Expires field in cookies via Twitter is not RFC822. Its format is `EEE, dd-MMM-yyyy HH:mm:ss z` (in US locale). How should I do for responding via Twitter APIs with valid Expires?

**Comment by weavejester** [comment]
You're feeding the result of `clj-http.client/post` directly into Ring. clj-http has a similar output to Ring, but it's not identical.

**Comment by func-hs** [comment]
Is there way to fix this invalid expires?

**Comment by weavejester** [comment]
You need to convert the return value from clj-http into a valid Ring response. If you just want to proxy the request, maybe you can adjust the clj-http middleware to limit how the response is transformed.

It really depends on what you're trying to do, though. The Clojure google group might be a good place to start asking. This isn't an issue with Ring, though, so I'll close it.
