### ISSUE TITLE
Why not allow blanks in keyword-syntax?

### ISSUE THREAD

**Issue by ulsa** [ring-clojure/ring#282]
I have params with user names that sometimes contain spaces, like "John Doe", and sometimes not, like "john3". In the resulting params map, I get a mix of strings and keywords, like `"John Doe"`, `:john3`, and `":john1"`:

```
(-> {:params {"myparam[John Doe]" "8" "myparam[john3]" "9" "myparam[:john1]" "7"}}
    ring.middleware.nested-params/nested-params-request
    ring.middleware.keyword-params/keyword-params-request)
=> {:params {:myparam {"John Doe" "8", :john3 "9", ":john1" "7"}}}
```

It is possible to create keywords with blanks:

```
(keyword "John Doe")
=> :John Doe
(keyword? (keyword "John Doe"))
=> true
```

Why aren't blanks allowed in keywords in this middleware? Would it create even weirder problems?

**Comment by weavejester** [comment]
Keywords with spaces are not valid keywords. You can create them, but only because the `keyword` function lacks runtime checks. This is a compromise around performance (see [CLJ-17](http://dev.clojure.org/jira/browse/CLJ-17)), and will likely be solved by clojure.spec, since that allows us to have runtime checks we can turn on or off.

**Comment by ulsa** [comment]
OK. So I guess the answer to my real question is to use `name` on the keys to get back the original string.

```
(name :john3)
=> "john3"
(name ":john1")
=> ":john1"
(name "John Doe")
=> "John Doe"
```

**Comment by weavejester** [comment]
You don't need to use `wrap-keyword-params`. That's only useful if you want keywords rather than strings.

Or access the `:form-params` key, which contains the unconverted form parameters.

**Comment by ulsa** [comment]
Oh, right, `:form-params`. Forgot that. Thx.

Anyway, this is an indication that a redesign might be needed. I think I should use IDs rather than names in this case.
