### ISSUE TITLE
Allow following symlinks in wrap-resource middleware

### ISSUE THREAD

**Issue by dmarjenburgh** [ring-clojure/ring#284]
I would like the `ring.middleware.resource/resource-request` to pass the :allow-symlinks? option to `ring.util.response/resource-response`. At the moment it is only passing the :root and :loader options.

The issue is that I have symlinks to resources in my development classpath. This problem arises for us when trying to upgrade from ring 1.4 to 1.6-RC1

**Comment by dmarjenburgh** [comment]
I can create a pull-request if this is a considered a worthwhile change.

**Comment by weavejester** [comment]
Yes, this is a bug that needs to be fixed, but I was going to tackle it today so no need for a PR :)
