### ISSUE TITLE
Only one single cookie present in request when using Pedestal with HTTP/2 in Jetty

### ISSUE THREAD

**Issue by claj** [ring-clojure/ring#285]
I'm using Pedestal with Jetty. Our application mysteriously was dropping cookies when there was more than one, presenting only one of many cookies to the application. The browsers (both Firefox and Chrome) reported they sent several cookies. The behaviour was present using HTTP/2 but disappeared when using only HTTP/1.1.

After some spurious Googling over the last months, and a report to the [pedestal project](https://github.com/pedestal/pedestal/issues/506), I think the issue is as follows:

According to the [Hypertext Transfer Protocol Version 2 (HTTP/2) section 8.1.2.5](https://http2.github.io/http2-spec/#rfc.section.8.1.2.5) there can be multiple COOKIE key in the header of such a request.

Despite the widespread use of Jetty, there are no bugs mentioning problems with disappearing cookies in HTTP/2.

It looks like Ring's [cookies.clj](https://github.com/ring-clojure/ring/blob/master/ring-core/src/ring/middleware/cookies.clj) expects the cookies to be transmitted as in HTTP/1.1 (ie one concatenated string in the Header section of the request).

I would assume that the correct way to get cookies in HTTP/2 would be to use the [.getCookies-method in the `HttpServletRequest`](https://tomcat.apache.org/tomcat-8.0-doc/servletapi/javax/servlet/http/HttpServletRequest.html#getCookies()) for Ring compability with HTTP/2 further on.

I'm not sure on how to continue from here, but could this be a reasonable theory?

**Comment by claj** [comment]
And more specific: would it be acceptable to rely on the `.getCookies`-method to access all of the cookies in an `HttpServletRequest` in the general case?

**Comment by weavejester** [comment]
Ring adapters concatenate headers of the same name in the request. Thus:

    Cookie: a=b
    Cookie: c=d

Is parsed into:

    {:headers {"cookie" "a=b, c=d"}}

The `wrap-cookies` middleware should be able to handle that fine.

Potentially there might be something wrong with the Pedestal Jetty library, maybe it's not working completely according to spec. Or there might be some other issue causing this problem. Could you come up with an example project that demonstrates the issue?

**Comment by weavejester** [comment]
This might possibly be a bug in Pedestal. The [servlet-request-headers](https://github.com/pedestal/pedestal/blob/f89d0abe244d0e8385d66a697724ef56180a00e5/service/src/io/pedestal/http/request.clj#L22) function doesn't appear to account for headers that have the same name. Contrast this to [get-headers](https://github.com/ring-clojure/ring/blob/master/ring-servlet/src/ring/util/servlet.clj#L13) in Ring. However, I'm not too familiar with Pedestal's source code, so it's possible I'm misreading it.

**Comment by weavejester** [comment]
The Ring spec could also be clearer on this issue. I'll correct it.

**Comment by claj** [comment]
Thanks for an extensive reply!

You are right, I mixed up the two different servlet abstractions, it looks like Pedestal's adapter is to blame, I'll investigate that further. I'm relieved to see ring's servlet adapter already handles this, although it feels a bit backward to concatenate the cookies string for each request in HTTP/2... but first I'll make sure the original problem is solved.

Thanks for clearifying the spec!

**Comment by weavejester** [comment]
This behaviour isn't specific to HTTP/2. HTTP 1.0 and 1.1 also support multiple headers of the same name. In HTTP, this:

    Foo: bar
    Foo: baz

Is semantically identical to:

    Foo: bar, baz

To quote the 1.1 spec:

> It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma.

Ring normalizes the headers, lowercasing the header names and then concatenating the values if there are multiple headers with the same name.

With Ring 2.0 this behaviour will likely change, as with HTTP/2 it makes more sense to parse all header values into a vector, rather than concatenate them into a string.

In future the spec might be something more like:

    {:ring.request/headers {"foo" ["bar" "baz"]}}

But that comes after Ring 1.6.0.
