### ISSUE TITLE
Solus not supported.

### ISSUE THREAD

**Issue by crusher42** [ring-clojure/ring#303]
i try to build but get Distribution 'Solus' not supported.

**Comment by weavejester** [comment]
Can you provide some more information. What do you mean by "build"?

**Comment by crusher42** [comment]
sorry i was running this ./make-ring.py --init and i got the output of Distribution 'Solus' not supported


and i forgot to add the url of the os i use https://solus-project.com/

**Comment by weavejester** [comment]
Are you certain you have the right project? There's no `make-ring.py` in this repository.

**Comment by crusher42** [comment]
or sorry this may not be the one im thing off
