### ISSUE TITLE
How to add a java servlet into a clojure ring project

### ISSUE THREAD

**Issue by astrekalova** [ring-clojure/ring#309]
I am integrating Togglz library into a Clojure Ring project to support feature toggles and would like to activate the Togglz admin console. According to the Togglz documentation it is necessary to add a servlet in the /WEB-INF/web.xml file for projects that don't support Servlet 3.0. I used the :uberjar-merge-with leiningen plugin to merge the file with the Togglz servlet configuration with the web.xml file autogenerated by leiningen. However, this was not sufficient to activate the admin console. I could not find much information on how to integrate a servlet from an external library into a Ring application. What would be the best way to do it?

**Comment by weavejester** [comment]
This isn't supported by the core Ring libraries. There may be other libraries around that do this, and if you have a servlet container you can run multiple servlets together, so you could run a Ring handler as a servlet, with the Togglz servlet.

You may find this question better asked in a more general forum, like the Clojure mailing list.
