### ISSUE TITLE
Case-sensitive HTTP headers

### ISSUE THREAD

**Issue by r-custodio** [ring-clojure/ring#311]
I would like to know if there is anyway to disable the lowercase headers, I know that headers is not case sensitive, but the way we are working with it (rabbitmq) it becomes case sensitive, with validations upon it.

**Comment by weavejester** [comment]
You could write your own adapter, but be aware of incompatibilities with Ring libraries. The HTTP spec says header names are case insensitive and Ring follows HTTP. If you're doing something that doesn't match up to HTTP, then you're going to have problems using Ring.
