### ISSUE TITLE
Can't use query parameters without a value

### ISSUE THREAD

**Issue by ElizabethForest** [ring-clojure/ring#312]
Hi!

In the browser, you are able to do `mywebsite.com?param` and `param` shows up as a query param with an empty string, but when using compojure param doesn't show up in `:query-params`.

Doing `mywebsite.com?param=` gives the query-params of `{:param ""}` which is expected, but then if you do `mywebsite.com?param=1&param2` you get `{:param 1, :param2 nil}`.

It feels a little inconsistent, and I would like to be able to use `mywebsite.com?param`.

I am using 1.6.0.

**Comment by weavejester** [comment]
Thanks. Can you explain why you think a query string of `param` should be parsed as a parameter map?

**Comment by weavejester** [comment]
Compatibility with existing APIs is a good reason, as is checking for existance of a particular query string.

I'll add this to my todo list, but I'll also accept a PR to alter the behavior of `ring.middleware.params/wrap-query-params` accordingly. Consistency around the empty string and nil is also something we could fix.
