### ISSUE TITLE
Document improvement for development and production setup

### ISSUE THREAD

**Issue by laliluna** [ring-clojure/ring#313]
I struggled to setup ring for development and production, as there are so many options. 

I tried to compile what I found into two pages https://github.com/laliluna/ring/wiki/Setup-for-development and https://github.com/laliluna/ring/wiki/Setup-for-production

In addition I structured the Home page to make it a bit easier to read.
https://github.com/laliluna/ring/wiki

The examples are more detailed to make it easier for unexperienced user to setup ring.

Let me know, if this is useful.

**Comment by weavejester** [comment]
Thanks for the documentation. I like the idea of a more real-world setup guide, but I noticed a few errors or unidiomatic examples when I was skimming the guides you had. I'm also not sure the Ring wiki is necessarily the right place for them.

**Comment by laliluna** [comment]
I would be happy, to improve what I created. In general I like the style of JavaScript projects providing all information on the project page. This is why I thought the right place in the wiki. Just let me know, how you would like to proceed.

**Comment by laliluna** [comment]
I removed pages with redundant information, updated an old ring on the getting startet page. There had been multiple pages on params and response generation The home and getting starting shows the latest clojar version now. I put every step into a separate commit to make this a bit more transparent. Let me know if anything can be improved.
