### ISSUE TITLE
Match HTTP caching spec when an ETag and If-Modified-Since are both provided

### ISSUE THREAD

**Issue by danielcompton** [ring-clojure/ring#322]
The [HTTP spec](http://www.rfcreader.com/#rfc2616_line4081) says:

> An HTTP/1.1 origin server, upon receiving a conditional request that includes both a Last-Modified date (e.g., in an If-Modified-Since or If-Unmodified-Since header field) and one or more entity tags (e.g., in an If-Match, If-None-Match, or If-Range header field) as cache validators, MUST NOT return a response status of 304 (Not Modified) unless doing so is consistent with all of the conditional header fields in the request.

I think there is a bug in the way the Ring not-modified middleware determines when to send a 304. If an If-None-Match (ETag) _or_ If-Modified-Since (Last-Modified) header is provided, then it works correctly. However if the client provides both, then the Ring middleware will return a 304 if either match, even though the HTTP spec says that all conditional header fields should match.

https://github.com/ring-clojure/ring/blob/7cada1b1723b3df996de794ad70edb0286e78455/ring-core/src/ring/middleware/not_modified.clj#L29-L39

See also https://stackoverflow.com/questions/824152/what-takes-precedence-the-etag-or-last-modified-http-header/1560098.

**Comment by weavejester** [comment]
Thanks for the report. This does appear to be an mistake, and I welcome any PRs to fix it :)
