### ISSUE TITLE
"Invalid anti-forgery token" seems to swallow other exceptions.

### ISSUE THREAD

**Issue by jjcroftiv** [ring-clojure/ring#336]
Hello -

I am trying to throw an "invalid username or password" exception during login.  However, after throwing the exception I get an "invalid anti-forgery token" error.  When the username/password is correct there is no issue.  So, I'm trying to understand where the anti-forgery token exception is thrown, because it seems to be swallowing my username/password exception.

Some code:

This function is called by the login-handler:

(defn datasource-username-password
  [datasource username password]
  {:pre [(and (some? username) (some? password))]}
  (log/debug "db-username-password")
  (log/trace (str "datasource: " datasource))
  (log/trace (str "username:   " username))
  (let [user       (datasource-username datasource username)]
    (if (nil? user) (throw (Exception. "Invalid username or password.")))
    (if (hashers/check password (user :usr_passwd))
      true
      (throw (Exception. "Invalid username or password.")))))

When the exception is triggered, I get this exception stack in my logs:

2018-07-08T19:17:35,016Z [qtp32294825-71] WARN  org.eclipse.jetty.server.HttpChannel - /login
java.lang.Exception: Invalid username or password.
	at io.coderz.auth.authc$datasource_username_password.invokeStatic(authc.clj:73)
	at io.coderz.auth.authc$datasource_username_password.invoke(authc.clj:65)
	at clojure.core$partial$fn__5561.invoke(core.clj:2617)
	at laminar.handlers$login_handler.invokeStatic(handlers.clj:53)
	at laminar.handlers$login_handler.invoke(handlers.clj:49)
	at compojure.response$eval2376$fn__2377.invoke(response.clj:47)
	at compojure.response$eval2298$fn__2299$G__2289__2306.invoke(response.clj:7)
        ....

But the response page is:

<h1>Invalid anti-forgery token</h1>

TIA -
John

**Comment by weavejester** [comment]
The [Ring-Anti-Forgery](https://github.com/ring-clojure/ring-anti-forgery) middleware is responsible for returning that page (unless you have some other custom middleware involved). It doesn't catch exceptions, so if something is intercepting your exception, it's between the anti-forgery middleware and your handler.

This isn't an issue with the Ring project itself, so I'm closing the issue. You may want to raise the question on the Clojure mailing list, the Ring mailing list, or the Clojure or Ring channels on the Clojurians slack channel, or any other forum for general help.

**Comment by jjcroftiv** [comment]
Thank you.
