### ISSUE TITLE
wrap-cookies result in a seq of strings as header value

### ISSUE THREAD

**Issue by Skinney** [ring-clojure/ring#338]
Currently, when using the `wrap-cookies` middleware, the value of the `Set-Cookie` header will be the cookie string wrapped in a seq.

While this works fine for the default `ring-jetty-adapter`, this causes a crash when running a ring app as a datomic ion.

I wrote a middleware that unwraps the string, and now it works in my datomic setup.

**Comment by weavejester** [comment]
This is the correct behavior in Ring. Response headers can either be a string, or a seq of strings. If receiving a seq as a header value is crashing datomic ions, it's a bug in their Ring adapter.
