### ISSUE TITLE
Trailing slash in wrap-resource

### ISSUE THREAD

**Issue by greenfork** [ring-clojure/ring#339]
If I specify `wrap-resource` in the chain of middlewares with an argument like `"public/"`, then it will serve static files from there during `lein run` just fine but will not serve them when run as an uberjar. Just `"public"` argument works fine for both cases.

I think that behaviour inconsistency in the first case should be eliminated.

**Comment by weavejester** [comment]
Something to trim the prefix when the middleware is applied would be acceptable.
