### ISSUE TITLE
ring.jetty.adapter any plans to upgrade to 9.2.25.v20180606?

### ISSUE THREAD

**Issue by ngunukula** [ring-clojure/ring#347]
Hi
 The current jetty-server version in ring.jetty-adapter is "org.eclipse.jetty/jetty-server "9.2.24.v20180105"", do we have any plans to upgrade to 9.2.25.v20180606. Looks like without this upgrade the Jetty-Server is exposing some vulnerabilities like: _in eclipse jetty, versions 9.2.x and older, 9.3.x (all configurations), and 9.4.x (non-default configuration with rfc2616 compliance enabled), transfer-encoding chunks are handled poorly. the chunk length parsing was vulnerable to an integer overflow. thus a large chunk size could be interpreted as a smaller chunk size and content sent as chunk body could be interpreted as a pipelined request. if jetty was deployed behind an intermediary that imposed some authorization and that intermediary allowed arbitrarily large chunks to be passed on unchanged, then this flaw could be used to bypass the authorization imposed by the intermediary as the fake pipelined request would not be interpreted by the intermediary as a request._

Let me know if I can go ahead and make these changes and do a PR

**Comment by weavejester** [comment]
Yes, any dependency update to resolve a potential vulnerability is welcome, especially if it's only a patch level change.

**Comment by based2** [comment]
https://github.com/ring-clojure/ring/pull/350
