### ISSUE TITLE
wrap-params "steals" form params in certain cases

### ISSUE THREAD

**Issue by jacovig** [ring-clojure/ring#360]
If you have two sets of routes, e.g.

(routes
  (wrap-defaults apis api-defaults)
  (wrap-defaults site site-defaults)
  (route/not-found "Page not found")
  )

if both 'apis' and 'site' have any POST part, the 'site' POST rules never get the form parameters, unless you use enctype="multipart/form-data". The slurp call in line 27 of ring.middleware.params seems to be unable to extract the parameters from body.

**Comment by weavejester** [comment]
Unfortunately this is unavoidable. Certain middleware needs to read the request body, and that operation is side-effectful. The only alternative to this is to cache the contents of the request body, which isn't always feasible or desirable.

You can resolve this by placing middleware that reads the request body, which I believe in your case would be `wrap-params` and `wrap-multipart`, at the top level.

**Comment by jacovig** [comment]
Ah, OK. Thanks. What a pitty!

Thank you James.
