### ISSUE TITLE
CompilerException when running `lein ring server-headless`

### ISSUE THREAD

**Issue by adeel** [ring-clojure/ring#361]
I just installed Leiningen and attempted to create a Compojure app.  Here is what I did:

    $ brew install leiningen
    $ lein new compojure myapp
    $ cd myapp
    $ lein ring server-headless

And here's the result of the last command: https://gist.github.com/adeel/ba01e1ca611b4ea455b94628ac09bbd4
Same thing with `lein ring`.  Before this I also tried using the install script [here](https://leiningen.org/#install).  Am I doing something wrong?  It's been a while since I've last used Clojure, so I'm sure that's probably the case.

I guess this is an issue with Ring which is why I posted here, but I can repost at the Compojure repository if necessary.

**Comment by weavejester** [comment]
It's not an issue with Ring, or Compojure, but one with the Compojure template. Update your Lein-Ring plugin to 0.12.5, or re-run `lein new compojure myapp` - the template should now be updated.

**Comment by adeel** [comment]
Cool, thanks for the quick fix!
