### ISSUE TITLE
Jetty adapter - handler is called a second time if unhandled exception is thrown

### ISSUE THREAD

**Issue by rsslldnphy** [ring-clojure/ring#364]
in the upgrade between versions `1.7.0` and `1.7.1`, `ring-jetty-adapter` upgraded its dependency on jetty from version `9.2.24.v20180105` to `9.4.12.v20180830`. as a result ring's behaviour when an unhandled exception is thrown has changed - the handler is now *called a second time* if an unhandled exception is thrown.

i've made a simple repo that reproduces the issue here: https://github.com/HealthUnlocked/ring-issue

if you run this repo and curl the endpoint, you'll see the handler logging twice, once before and once after the exception is thrown. if you change the `ring` dependencies to `1.7.0` and try the same, you'll see the logging once.

we encountered this as a result of a bug with one of our endpoints that sends an email and then tries to return an unserializable response - causing an unhandled exception. since upgrading the email gets sent twice every time the endpoint is called.

i've tried searching documentation and i can't even tell if this is intentional behaviour on jetty's part (but i can't believe that it would be?) and i realise this is not really ring's responsibility but i don't know if there's something that ring could do to protect its users from this behaviour? i will raise an issue on jetty's github as well.

**Comment by rsslldnphy** [comment]
For a while I was convinced that this call to `.setHandled` needs to be in a `try...finally` block to make sure it's called even on error:

https://github.com/ring-clojure/ring/blob/3d79b87442341a1f407a1effed7b390086059f51/ring-jetty-adapter/src/ring/adapter/jetty.clj#L22-L28

However I tried making that change and running locally with a patched version of `ring-jetty-adapter` and still got the logging twice.

Have been trying to dig into the `jetty` source code but my ability to read Java is... poor. However I believe the first call to the handler comes from here:

https://github.com/eclipse/jetty.project/blob/0809228549c8dbb7ffede1ccd6d4ff57d6a60474/jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java#L370

and the second from here:

https://github.com/eclipse/jetty.project/blob/0809228549c8dbb7ffede1ccd6d4ff57d6a60474/jetty-server/src/main/java/org/eclipse/jetty/server/HttpChannel.java#L425

(discovered this by logging the stacktrace of an exception in the handler's logging)

**Comment by weavejester** [comment]
Thanks for the investigation. It looks like we'd need to write something like:

```clojure
(defn- ^AbstractHandler proxy-handler [handler] 
  (proxy [AbstractHandler] [] 
    (handle [_ ^Request base-request request response] 
      (when-not (= (.getDispatcherType request) DispatcherType/ERROR)
        (let [request-map  (servlet/build-request-map request) 
              response-map (handler request-map)] 
          (servlet/update-servlet-response response response-map) 
          (.setHandled base-request true))))))
```

**Comment by rsslldnphy** [comment]
👍 no problem. confirmed on the [jetty issue](https://github.com/eclipse/jetty.project/issues/3541) that it's intentional and their suggestion is the same as yours. happy to put a PR together.

**Comment by weavejester** [comment]
I'd be glad to have a PR! Ideally it should fix both sync and async handlers.

**Comment by rsslldnphy** [comment]
PR submitted! I haven't used async handlers in `ring` before so I may be missing something, but having copied and amended a test case for them it doesn't seem like they are affected in the same way? Unless I'm getting it wrong. I've left the test case in so that if anything changes in this respect, it will be caught.

**Comment by yannvanhalewyn** [comment]
We ran into this too, thanks for the fix! 🎉
