### ISSUE TITLE
Releasing a new version of ring.core ?

### ISSUE THREAD

**Issue by tommy** [ring-clojure/ring#367]
Would you mind releasing the latest commits to a new version on Clojars? (In particular I'm looking for the removal of the clj-time dependency.)

And, thank you for your work on this project!

**Comment by weavejester** [comment]
The clj-time change needs to be tested a little more before it can be released, and I'd like to get a couple of fixes in the next patch release. I expect to be able to release it before May.

**Comment by tommy** [comment]
Alright, thanks for the update!

**Comment by kanwei** [comment]
Bumping to also request a new release (or SNAPSHOT) to remove joda-time. Will also test and report back. Thanks!

**Comment by darkleaf** [comment]
any updates?

**Comment by weavejester** [comment]
Just released 1.8.0. Apologies for how long this took to push out.
