### ISSUE TITLE
Joda classnotfound on 1.8.0

### ISSUE THREAD

**Issue by mmmdreg** [ring-clojure/ring#383]
I can see explicit joda/clj-time dependency was removed as part of #358, released in 1.8.0. 

My usage of cookies is only via ring-defaults `(wrap-defaults (assoc api-defaults :cookies true))`. 

For some reason, it fails when loading ring.middleware.session (which loads r.m.cookie), with ClassNotFoundException: org.joda.time.DateTime. 

I have tried: 
- adding joda dependency (works but should not be necessary)
- clearing my local repo and recalculating classpath etc (does not work)
- putting a local version of ring-core (with deps.edn created from project.clj) and depending on it with :local/root in my deps.edn (works)

Since the last test (with vendored ring-core) works, I can’t see why it doesn’t work when depended on via maven. 

Since I am not actually using joda, does anyone have any ideas that don’t involve requiring joda?

**Comment by weavejester** [comment]
Hi, sorry for the late reply. Could you possibly set up an example repository that demonstrates the problem? It's hard to determine the issue without some sample code that can reproduce it.

**Comment by mmmdreg** [comment]
Can't seem to reproduce this at home so will close for now. I will investigate my work set up a bit more to see if I can figure it out.

**Comment by mmmdreg** [comment]
Novice error. There was a stale ‘classes’ lying around on the deps src path.

**Comment by weavejester** [comment]
Good to know it was a false alarm. That's tripped up me before as well.

**Comment by jngbng** [comment]
I had the same problem, but resolved after ``lein clean``.
