### ISSUE TITLE
ring-jetty-adapter should expose `setExcludeCipherSuites`

### ISSUE THREAD

**Issue by MIJOTHY-V2** [ring-clojure/ring#404]
[a91d874](https://github.com/ring-clojure/ring/commit/a91d874a4e906dec8fe46ce9fd98d3aac7d729e5) added the ability to extend the list of excluded ciphers by calling out to [`SslContextFactory.addExcludeCipherSuites`](https://www.eclipse.org/jetty/javadoc/9.4.28.v20200408/org/eclipse/jetty/util/ssl/SslContextFactory.html#addExcludeCipherSuites(java.lang.String...)). However, this operation is purely additive. There are use-cases for replacing the set of excluded cipher suites, and `SslContextFactory` exposes this functionality through [`SslContextFactory.setExcludeCipherSuites`](https://www.eclipse.org/jetty/javadoc/9.4.28.v20200408/org/eclipse/jetty/util/ssl/SslContextFactory.html#setExcludeCipherSuites(java.lang.String...)). 

The particular use-case I'm interested in is the running of `jetty` on IBM JVMs. Since the IBM JVM prefixes its cipher suites with `SSL_`, and ciphers matching this regex are [considered naughty](https://github.com/eclipse/jetty.project/blob/jetty-9.4.x/jetty-util/src/main/java/org/eclipse/jetty/util/ssl/SslContextFactory.java#L126), `jetty` servers interacted with via `ring-jetty-adapter` are unable to run on https on IBM JVMs without severe hacks (think mutating via `:configurator` sort of hacks).

Since this functionality is exposed by `jetty` under the hood anyway, I reckon it wouldn't be a bad thing to expose it via `ring-jetty-adapter`. Something along the lines of `:override-exclude-ciphers` and `override-exclude-protocols`? Happy to PR.

Example jetty issues relating to the IBM thing:
* https://github.com/eclipse/jetty.project/issues/3817
* https://github.com/eclipse/jetty.project/issues/2921

**Comment by weavejester** [comment]
Those additional options seem fine to me.
