### ISSUE TITLE
wrap-reload not work on checkouts project 

### ISSUE THREAD

**Issue by paomian** [ring-clojure/ring#418]
i have two project A and B.
A is dependent on B.and A path have soft links to B in `checkouts/B/src`
when i modify A ，it work well.but when i modify B it does not work.

**Comment by weavejester** [comment]
You'll need to provide more information. How are you calling `wrap-reload`? What's the value of the `:dirs` option?

**Comment by paomian** [comment]
```clojure
(defn wrap-dir-reload
  [app]
  (if (or (config/production?) (config/stage?))
    app
    (try
      ((eval '(do (use '[ring.middleware.reload])
                  wrap-reload))
       app
       {:dirs ["src" "checkouts/B/src"]})
      (catch Exception ex
        app))))

(def reload-app (-> some-other-middlewares wrap-dir-reload))
```
my reload middleware. and

**Comment by paomian** [comment]
I'm sorry.this is my problem. because my handler will call self other path when start.wrap-reload middleware will reload my function.this time the handler is not ready.so it block here.
