### ISSUE TITLE
Ring-codec dependency in new release v1.9.0

### ISSUE THREAD

**Issue by malesch** [ring-clojure/ring#431]
Is it on purpose that with the new release v1.9.0 the depedency ring-codec did not get an upgrade?

Reason:
The fix [#25](github/ring-clojure/ring-codec#25) would prevent an ugly NPE which I otherwise would have to manually catch. Alternatively a new release for ring-codec would allow to override the deps in ring-core.

Thanks!

**Comment by weavejester** [comment]
No, that's an oversight. As it's a bug fix, I can release Ring-Codec 1.1.3, and Ring 1.9.1.

**Comment by malesch** [comment]
Great, many thanks!

**Comment by weavejester** [comment]
Released 1.9.1.
