### ISSUE TITLE
Add Clojure CLI demo in Setup-for-development.md

### ISSUE THREAD

**Issue by erronppl** [ring-clojure/ring#437]
This [branch](
https://github.com/erronppl/ring-wiki/tree/demo-clojure-cli) describes how to set up a minimal project using Clojure deps and CLI. Could you update the project Wiki ?

**Comment by weavejester** [comment]
Why don't you update the wiki?

**Comment by erronppl** [comment]
I didn't see the "Edit" button when I first looked at it. I have updated the Wiki as presented by the PR. See https://github.com/ring-clojure/ring/wiki/Setup-for-development#setup-using-clojure-deps-and-cli
