### ISSUE TITLE
Callback after response transmission

### ISSUE THREAD

**Issue by bandoos** [ring-clojure/ring#459]
I was wondering is there is a way to execute a callback after an http response is successfully transmitted to the client.

My use case is the following:
- My web request handler processes uploaded files, transforms them and then creates a zip archive of the results. 
- The response is a `file-response` sending the archive back to the client
- After the response is transmitted i'd like to delete the archive from the server working directory

Right now i simply schedule the deletion after a few minutes so i'm reasonably sure the response was transmitted, but maybe there is a way (maybe with the 3-arity handler contract?) in which I can do it immediately after response was delivered.

Thanks in advance.

**Comment by weavejester** [comment]
You can reify `ring.core.protocols/StreamableResponseBody`:

```clojure
(require '[clojure.java.io :as io])
(require '[ring.core.protocols :as p])

(defn handler [request file callback]
  {:status 200
   :headers {}
   :body (reify p/StreamableResponseBody
           (write-body-to-stream [_ _ ^java.io.OutputStream os]
             (io/copy some-file os)
             (.close os)
             (callback request file)))})
```

**Comment by bandoos** [comment]
Amazing, thanks for the fast response!
