### ISSUE TITLE
Broken link on https://github.com/ring-clojure/ring/wiki/Creating-responses

### ISSUE THREAD

**Issue by jfhector** [ring-clojure/ring#466]
Hello!

Thanks for your great work on Ring.

I've noticed a broken link in the docs:

At the bottom of this page ...
https://github.com/ring-clojure/ring/wiki/Creating-responses

... there is this link
[ring.util.response API documentation](http://ring-clojure.github.com/ring/ring.util.response.html)

... but that link points to a 404 page.

The same link is also at the top of the page.

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/30028540/171495480-e06ad3c2-8cd0-4cc9-8dc7-05a4bfc77a54.png">

The target URLs should probably be:
http://ring-clojure.github.io/ring/ring.util.response.html

**Comment by weavejester** [comment]
Thanks for the fix.
