### ISSUE TITLE
Catch up rename of `websocket-request?` to `upgrade-request?` in Wiki

### ISSUE THREAD

**Issue by viesti** [ring-clojure/ring#500]
Hi, and thank you for this and other great Clojure projects! :)

I noticed that in the [Websocket Wiki page](https://github.com/ring-clojure/ring/wiki/WebSockets), `websocket-request?` is used, while it got renamed to upgrade-request? https://github.com/ring-clojure/ring/blob/7e4139e6314eda9fe08cc3422edd372dac3bbf84/CHANGELOG.md?plain=1#L45

I see an edit button available in the Wiki, but not sure if it works for me, so decided to let you know :)

Thanks!

**Comment by weavejester** [comment]
Looks like the Wiki page was updated successfully. Thanks for the correction!
