### ISSUE TITLE
wrap-multipart-params creates an empty file when an empty file input is submitted

### ISSUE THREAD

**Issue by rutchkiwi** [ring-clojure/ring#502]
When you have an HTML form with enctype="multipart/form-data" and a file input, then submit the form without any files, wrap-multipart-params still creates a file of 0 length:

```
"image" {:filename "",
                             :content-type "application/octet-stream",
                             :tempfile #object[java.io.File
                                               0x2a85b8fb
                                               "/var/folders/hk/ssb3bsh12bs8l3pd4wct1_0m0000gn/T/ring-multipart-12791286223966256629.tmp"],
                             :size 0},
```

I was expecting this to be nil in the case of no file being uploaded, not an empty file. 
Seems somewhat reasonable but it is annoying to handle in code, as now I need to be extra carefull and check the size before I access the file.
Would you be open to a PR changing this behaviour to give you `:image nil` instead?

**Comment by weavejester** [comment]
Is there a way of reliably determining, for all browsers, whether the file has been omitted from the input, or whether a zero-byte file has been submitted?

**Comment by rutchkiwi** [comment]
ok thats fair! just wasted an hour on this, so thought i would ask about it to save someone else the time. But you're likely right in that it cant be 100% accurately determined.

Thanks for the quick reply!
