### ISSUE TITLE
Update jetty-server

### ISSUE THREAD

**Issue by KGOH** [ring-clojure/ring#506]
Currently jetty-server has 11.0.21 version, which fixes a number of bugs
https://github.com/jetty/jetty.project/releases/tag/jetty-11.0.21

**Comment by ieugen** [comment]
While ring will eventually pick this up, you can explicitly depend on that version of jetty in your code and it will override the version that comes with ring-jetty-adapter. 

I do think ring-jetty-adapter should not ship with buggy versions of jetty, but maintenance is costly.

**Comment by KGOH** [comment]
> ring-jetty-adapter should not ship with buggy versions of jetty
oh what a wonderful world would it be

Yeah, explicit dependency did work for me. Thanks

**Comment by weavejester** [comment]
From the Jetty changelog, there doesn't appear to be anything in the Jetty release that would effect Ring, but I'll release a new version anyway.
