### ISSUE TITLE
ring.util.response generates non-lowercase headers, contradicting the spec

### ISSUE THREAD

**Issue by opqdonut** [ring-clojure/ring#514]
According to the spec, the keys in the headers map should be lowercased.

https://github.com/ring-clojure/ring/blob/master/SPEC.md#headers-1

At least the ring.util.response/content-type util produces a mixed-case header, `"Content-Type"`. Probably other utils do the same.

https://github.com/ring-clojure/ring/blob/f7dfe7c9b98c335e4573e61d94c523d5df9a6667/ring-core/src/ring/util/response.clj#L184

We discovered this while looking into metosin/ring-http-response#35 .

Would a PR be welcome?

**Comment by weavejester** [comment]
Yes, but in this case the error is with the spec, not the middleware. It looks like when I was converting the spec to markdown a mistake was made.

**Comment by weavejester** [comment]
To clarify further, I converted the current markdown-based spec from work I was doing on Ring 2.0. My original plan for 2.0 was to make the response headers consistently lowercase to make them easier to access by middleware. However, this would be a breaking change from the 1.x specs.

I eventually abandoned the work on Ring 2.0, as the breaking changes I wanted weren't enough to justify running two separate specs, or trying to make Ring work with both. I may return to it in future at some point.

**Comment by weavejester** [comment]
> [@weavejester](https://github.com/weavejester) should https://github.com/ring-clojure/ring/blob/master/SPEC.md#headers be updated as well ("A Clojure map of lowercased header name strings to corresponding header value strings.")?

No, that's correct, because it's for the request, not the response.
