### ISSUE TITLE
Cannot resolve jakarta.servlet.AsyncContext

### ISSUE THREAD

**Issue by lost22git** [ring-clojure/ring#516]
|key|version|
|----|----|
|java|21|
|clojure|v1.12.0.1479|
|babashka|v1.12.195|

# code

```clojure
#!/usr/bin/env bb
(require '[cheshire.core :as json])
(require '[babashka.deps :as deps])
(deps/add-deps '{:deps {ring/ring-core {:mvn/version "1.13.0"}
                        ring/ring-jetty-adapter {:mvn/version "1.13.0"}}})

(use 'ring.middleware.params)
(use 'ring.adapter.jetty)

(defn halo [req]
  {:status 200
   :headers {:content-type "application/json"}
   :body (-> {:msg (str "Halo " (get-in req [:query-params :name]))}
             json/encode)})
(def app
  (-> halo
      wrap-params))
(run-jetty app {:port 8000})
```

# error msg

![Screenshot_20241123-024655__01](https://github.com/user-attachments/assets/bb71df39-58e7-4c23-8149-97f73aeeac6b)

**Comment by weavejester** [comment]
Not every Java library works with GraalVM/Babashka. When developing for Babashka you need to be careful to use compatible libraries. It may be that the Jetty adapter is simply incompatible with Babashka.

However, Babashka comes with [http-kit](https://github.com/http-kit/http-kit) buillt in, an alternative Ring adapter. You may be able to solve your issue by replacing `ring.adapter.jetty/run-jetty` with `org.httpkit.server/run-server`.
